import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Login from './Login';


export default function Home() {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next Auth!
        </h1>
        <div>
          <p>This is the model for authentication.</p>
        </div>
        
        <Login />

      </main>
    </div>
  )
}
